"""
Sort a turtle file generated by rdflib.
"""

import sys

# read in the file
lines = sys.stdin.readlines()
if not lines:
    sys.exit(1)

chunks = []
while lines:
    blank_line_index = lines.index("\n")
    chunks.append(lines[0 : blank_line_index + 1])
    lines = lines[blank_line_index + 1 :]

# print out the "# baseURI:" and "# imports:"
print("".join(chunks[0][:-1]))
del chunks[0]

# sort
chunks.sort()

# extract @prefix lines
prefix_chunks = []
prefix_indx = []
for i, chunk in enumerate(chunks):
    if chunk[0].startswith("@prefix"):
        prefix_chunks.extend(chunk)
        prefix_indx.append(i)

# remove the lines we found
for i in reversed(prefix_indx):
    del chunks[i]

# remove the blank lines
prefix_chunks = [chunk for chunk in prefix_chunks if chunk != "\n"]

# sort them and remove the duplicates
prefix_chunks.sort()
prefix_chunks = list(dict.fromkeys(prefix_chunks))
print("".join(prefix_chunks))

# print the rest
for chunk in chunks:
    print("".join(chunk[:-1]))
